### ISSUE TITLE
Removed your package and Flarum does not refresh the logout and activation status

### ISSUE THREAD

**Issue by Benoit1980** [FriendsOfFlarum/passport#20]
Version Flarum Beta 16

I have just installed your latest package and could not get it to work unforunately.
I decided to remove it from the admin panel and now the logout sessions and account activations do not refresh their status unless I manually refresh the(reload) the page.

ie: I log out, the user profile still shows in the navbar, I refresh the page, the user name disappear.

Any idea how I can get the forum back to normal?

Thank you.

**Comment by Benoit1980** [comment]
A very problematic package with Beta16. I reinstalled it, uninstalled it, emptied the cache, but it killed my forum sessions. When I logout I have to refresh the page to get the logout to show as "logged out". Same with the registration links, they won't show they have been clicked until you manually refresh the page.

**Comment by clarkwinkelmann** [comment]
That's very odd. This extension shouldn't affect how Flarum refreshes the page after a login or logout.

Do you see any error in the browser javascript console (under developer tools) or in the Flarum log file?

Have you tried other social logins (with FoF OAuth for example) on the same forum? Because that other extension also works the same way so any issue should also happen with it.

**Comment by Benoit1980** [comment]
Thanks for the reply.
I did not use the other package no.
What I find strange is that even if I reinstall your package, it will not show up in the admin panel(even after clearing the cache).

This is what I get on logout:
Request URL: https://xxxxxxxxxxx.com/forum/logout?token=U0l9t73a0vCuy45DyQgNEaNZjd84N3r0b52VhJEl
Request Method: GET
Status Code: 302

**Comment by clarkwinkelmann** [comment]
Maybe the Composer command to install or remove the package is experiencing an error? Do you see any error or warning when running Composer?

it's normal for the logout to happen with a redirect through /logout. The `token` will be unique each time because it's the Flarum CSRF token. After the redirect the page should correctly show you logged out.

The logout part does not interact with social providers at all so if it's broken it must be something different. Only login is impacted by social logins.

**Comment by luceos** [comment]
Please post the output of php flarum info.

**Comment by Benoit1980** [comment]
I am pasting the flarum info after the fof/passport installation.

As you can see, it does not show up anymore in the flarum info even after install.


composer require fof/passport
Warning from https://repo.packagist.org: You are using an outdated version of Composer. Composer 2 is now available and you should upgrade. See https://getcomposer.org/2
Using version ^0.6.0 for fof/passport
./composer.json has been updated
Loading composer repositories with package information
Warning from https://repo.packagist.org: You are using an outdated version of Composer. Composer 2 is now available and you should upgrade. See https://getcomposer.org/2
Updating dependencies (including require-dev)
Package operations: 6 installs, 0 updates, 0 removals
  - Installing paragonie/random_compat (v9.99.100): Loading from cache
  - Installing psr/http-client (1.0.1): Loading from cache
  - Installing guzzlehttp/promises (1.4.1): Loading from cache
  - Installing guzzlehttp/guzzle (7.3.0): Loading from cache
  - Installing league/oauth2-client (2.6.0): Loading from cache
  - Installing fof/passport (0.6.0): Loading from cache
paragonie/random_compat suggests installing ext-libsodium (Provides a modern crypto API that can be used to generate random bytes.)
Writing lock file
Generating autoload files
68 packages you are using are looking for funding.
Use the `composer fund` command to find out more!
>>>>>>>
php flarum info
Flarum core 0.1.0-beta.16
PHP version: 7.3.28
Loaded extensions: Core, date, libxml, openssl, pcre, zlib, filter, hash, pcntl, readline, Reflection, SPL, session, standard, bcmath, bz2, calendar, ctype, curl, dom, enchant, mbstring, fileinfo, ftp, gd, gettext, iconv, imap, intl, json, exif, mysqlnd, PDO, Phar, posix, pspell, shmop, SimpleXML, soap, sockets, sqlite3, sysvmsg, sysvsem, sysvshm, tidy, tokenizer, xml, xmlwriter, xsl, mcrypt, mysqli, pdo_mysql, pdo_sqlite, wddx, xmlreader, xmlrpc, igbinary, imagick, mailparse, msgpack, PDFlib, zip, memcached, mysql, ionCube Loader, Zend OPcache
+----------------------+------------------+--------+
| Flarum Extensions    |                  |        |
+----------------------+------------------+--------+
| ID                   | Version          | Commit |
+----------------------+------------------+--------+
| flarum-flags         | v0.1.0-beta.16   |        |
| flarum-sticky        | v0.1.0-beta.16   |        |
| fof-user-directory   | 0.6.2            |        |
| flarum-approval      | v0.1.0-beta.16   |        |
| flarum-bbcode        | v0.1.0-beta.16   |        |
| flarum-emoji         | v0.1.0-beta.16   |        |
| flarum-lang-english  | v0.1.0-beta.16   |        |
| flarum-lock          | v0.1.0-beta.16   |        |
| flarum-markdown      | v0.1.0-beta.16.1 |        |
| flarum-mentions      | v0.1.0-beta.16   |        |
| flarum-statistics    | v0.1.0-beta.16   |        |
| flarum-subscriptions | v0.1.0-beta.16   |        |
| flarum-suspend       | v0.1.0-beta.16   |        |
| flarum-tags          | v0.1.0-beta.16   |        |
+----------------------+------------------+--------+
Base URL: https://xxxxx.com/forum
Installation path: /home/xxxxx/public_html/forum
Debug mode: off


Thank you.

**Comment by clarkwinkelmann** [comment]
Are you able to update to Composer v2? It's not clear if Composer is the issue here but upgrading to Composer v2 won't hurt and it'll speed up future installs and updates.

If you haven't already, you could also try setting `debug` to `true` in `config.php` and try to login/logout/enable/disable extension again to see if there's any difference.

From your Composer output it doesn't seem like Composer experienced any error but if the extension doesn't show up in the admin panel it's probably Composer related in some way.

**Comment by Benoit1980** [comment]
Unfortunately I cannot upgrade to composer 2 as it breaks some of my previous projects.

**Comment by Benoit1980** [comment]
It is ok, no worry I will have to delete the forum as I am just too stuck with this issue. Thanks again.

**Comment by clarkwinkelmann** [comment]
I have just tested this extension again for the Flarum 1.0 update and did not find any issue.

I did experience something similar to you because I had the Masquerade extension enabled with "force profile fill" which *does* prevent logging out since every time I click on logout I am redirected to my profile. But I doubt this was your issue since it would be obvious the logout is always redirected to the Masquerade page.

I'm closing this for now but feel free to re-open if you try again and find additional details!
